### ISSUE TITLE
[request] Add Antenaplay

### ISSUE THREAD

**Issue by redmusicxd** [cralin/plugin.video.TVOnline.ro#1]
Hi, i was wondering if you could integrate antenaplay in your addon using the URLs from below attached Charles session.
[AntenaPlay.chls.zip](https://github.com/cralin/plugin.video.TVOnline.ro/files/6045548/AntenaPlay.chls.zip)

**Comment by cralin** [comment]
Hi,

I don't think the method you used to obtain those URLs is going to be sustainable for the long run.

However, assuming that some day I could get access to a **valid** user account on the antenaplay.ro website, I wouldn't mind taking a shot at it.

**Comment by redmusicxd** [comment]
Yeah, you are right, don't know what I was thinking, if you want you could
take a look at my JavaScript Implementation for this here
https://github.com/redmusicxd/iptv_ro/blob/main/antena.js

**Comment by cralin** [comment]
Unless the .js file mentioned by you would somehow help me obtain a valid user account that I can use to play the streams available after the user account is successfully authenticated to the web site, I'm not really sure what I can do with it.

**Comment by redmusicxd** [comment]
Ok, sorry to bother you then.

**Comment by redmusicxd** [comment]
Just a note, you could just use the free account.

**Comment by cralin** [comment]
Have you tried to use a free account in order to log-in with a web browser on the portal and then play a stream ?

Does it show you anything else other than a big button to pay for a subscription and a link  that is supposed to allow you to play the stream for 2 minutes but it actually does not work ?

I'll be more than happy to reconsider this request as soon as the situation changes and the minimum prerequisites for starting development are fulfilled.

**Comment by redmusicxd** [comment]
Yes, of course i did, that’s how I wrote my script.

**Comment by redmusicxd** [comment]
What are describing happens if you are not logged in.

**Comment by redmusicxd** [comment]
On page load
![Screenshot_20210302_235154](https://user-images.githubusercontent.com/29458132/109720171-6db67000-7bb2-11eb-86c7-c1ccc560ec91.png)
After clicking "Incepe vizionarea"
![Screenshot_20210302_235237](https://user-images.githubusercontent.com/29458132/109720143-62634480-7bb2-11eb-9770-12d4c4ff2bf6.png)

**Comment by cralin** [comment]
The clicking on "Incepe vizionarea" text does not work in my case (it seems to be just a blue string that does not trigger anything).

Is this somehow browser or location dependent ?

**Comment by redmusicxd** [comment]
browser dependent, don't think so.
location as in geographical location? then yes

**Comment by redmusicxd** [comment]
but i do have one thing to add, i'm using the uMatrix addon and i had to whitelist zencdn.net

**Comment by redmusicxd** [comment]
as that's where the video player script comes from.
