### ISSUE TITLE
Suport ProTV Plus

### ISSUE THREAD

**Issue by Pappbox** [cralin/plugin.video.TVOnline.ro#10]
Salut, am instalat azi TVOnline pe KODI pe un XIaomi MI BOX 4S

DIGI ONLINE imi merge fara probleme, dar canalele PRO nu merg. 

EMAILul si Parola sunt verificate de mai multe ori, imi arata si lista de canale, dar streamul nu porneste si intra in eroare

Acceasi VPN cu acceasi login merg pe protvplus direct

**Comment by cralin** [comment]
Salut,

Problema este rezolvata cu versiunea 19.2.4.
