### ISSUE TITLE
The add-on stopped working since around a week.

### ISSUE THREAD

**Issue by Xdrqgol** [cralin/plugin.video.TVOnline.ro#12]
I have run the addon for around a year now using ExpressVPN to connect.
As I remember the last time I successfully used it was on 3rd of May.

Have tried to use it on the 22nd and , it seems it doesn't load the video feed...remains on the loading animation and then it says TvOnline got an error to check the error log.

**plugin.video.TVOnline.ro.log**
20220523_140600 digionline__getStreamDetails DEBUG: Headers: {'User-Agent': 'okhttp/4.8.1'}
20220523_140600 digionline__getStreamDetails DEBUG: URL: https://digiapis.rcs-rds.ro/digionline/api/v13/streams_l_3.php
20220523_140600 digionline__getStreamDetails DEBUG: Method: GET
20220523_140600 digionline__getStreamDetails DEBUG: Parameters: {'action': 'getStream', 'id_stream': '4', 'platform': 'Android', 'version_app': '1.0', 'i': 'Sony_BRAVIA_VH1_1653239783_f34c020f62e54400976c356ca16871c009b5779ed59a46ec86e0e2f44ddb79f37e26ff97353048f5a65c5d00173b0a276d91b', 'sn': 'ro.rcsrds.digionline', 's': 'app', 'quality': 'all'}
20220523_140824 init_AddonCookieJar DEBUG: Enter function
20220523_140824 init_AddonCookieJar DEBUG: [ Addon cookies file ] cookies_file = /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.TVOnline.ro/digionline.ro_cookies.txt
20220523_140824 init_AddonCookieJar DEBUG: [ Addon cookiejar ] Loaded cookiejar from file: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.TVOnline.ro/digionline.ro_cookies.txt
20220523_140824 init_AddonCookieJar DEBUG: Enter function
20220523_140824 init_AddonCookieJar DEBUG: [ Addon cookies file ] cookies_file = /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.TVOnline.ro/protvplus.ro_cookies.txt
20220523_140824 init_AddonCookieJar DEBUG: [ Addon cookiejar ] Loaded cookiejar from file: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.TVOnline.ro/protvplus.ro_cookies.txt
20220523_140824 <module> DEBUG: Enter function
20220523_140824 <module> DEBUG: === SYSINFO ===  Addon version: 19.2.6
20220523_140824 <module> DEBUG: === SYSINFO ===  System.BuildVersion: 19.3 (19.3.0) Git:20211024-49a04cd6a7
20220523_140824 <module> DEBUG: === SYSINFO ===  System.BuildDate: 2021-10-24
20220523_140825 init_AddonCookieJar DEBUG: Enter function
20220523_140825 init_AddonCookieJar DEBUG: [ Addon cookies file ] cookies_file = /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.TVOnline.ro/digionline.ro_cookies.txt
20220523_140825 init_AddonCookieJar DEBUG: [ Addon cookiejar ] Loaded cookiejar from file: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.TVOnline.ro/digionline.ro_cookies.txt
20220523_140825 init_AddonCookieJar DEBUG: Enter function
20220523_140825 init_AddonCookieJar DEBUG: [ Addon cookies file ] cookies_file = /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.TVOnline.ro/protvplus.ro_cookies.txt
20220523_140825 init_AddonCookieJar DEBUG: [ Addon cookiejar ] Loaded cookiejar from file: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.TVOnline.ro/protvplus.ro_cookies.txt
20220523_140825 <module> DEBUG: Enter function
20220523_140825 <module> DEBUG: === SYSINFO ===  Addon version: 19.2.6
20220523_140825 <module> DEBUG: === SYSINFO ===  System.BuildVersion: 19.3 (19.3.0) Git:20211024-49a04cd6a7
20220523_140825 <module> DEBUG: === SYSINFO ===  System.BuildDate: 2021-10-24

**service.plugin.video.TVOnline.ro.log**
please see it attached
[service.plugin.video.TVOnline.ro.log](https://github.com/cralin/plugin.video.TVOnline.ro/files/8755913/service.plugin.video.TVOnline.ro.log)
.

**Comment by Xdrqgol** [comment]
[plugin.video.TVOnline.ro.log](https://github.com/cralin/plugin.video.TVOnline.ro/files/8756037/plugin.video.TVOnline.ro.log)
Please see it attached

**Comment by cralin** [comment]
adauga te rog si fisierul  kodi.log de pe acelasi kodi de pe care ai luat log-urile addon-ului

**Comment by cralin** [comment]
Am gasit problema, iti scriu pe forum

**Comment by Xdrqgol** [comment]
Fixed, A trebuit sa schimb protocolul in VPN si , merge ca uns! KEEP UP THE GOOD WORK!

mersi frumos pt ajutor.
