### ISSUE TITLE
 [digionline.ro] => Incomplete configuration => Please configure all fields for digionline.ro account.

### ISSUE THREAD

**Issue by dilighiani** [cralin/plugin.video.TVOnline.ro#14]
Later Edit: Rezolvat. Poate fi sters acest issues.
Am gasit rezolvarea intr-un alt Issue inchis. 
Multumesc!

##################################
Salut,
In primul rand mega-felicitari pentru proiect!

* In clipa de fata incerc un test cu un Kodi pe Windows si apoi dupa ce voi reusi il voi configura pe un Debian aflat in alta locatie. Problema pe care o acum este pe Windows pe care ruleaza Kodi 19.4.
Am urmat pasii din Wiki si am instalat cu succes, reusesc sa obtin lista de canale, totusi atunci cand dau Play oricarui canal primesc eroarea  [digionline.ro] => Incomplete configuration => Please configure all fields for digionline.ro account.
Mentionez ca-n setarile din plugin.video.TVOnline.ro am completat doar Username-ul si parola care 100% functioneaza OK din browser. Nu am completata nimic la campurile "Device Manufacturer", "Model", "Android version".

* https://imgur.com/a/Y4wuXAU - aici sunt 2 Printscreen-uri. Primul este cu eroarea si al doilea este cu Setarile din TVOnline.ro

Please help!

* Acestea sunt ultimele linii din logul de la plugin.video.TVOnline.ro
20220810_180147 digionline__read_stateData DEBUG: Reading from 'C:\Users\admin\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.TVOnline.ro\digionline.ro_state.txt'
20220810_180147 digionline__read_stateData DEBUG: Return data: {'exit_status': 0, 'state_data': {'deviceID': '', 'deviceManufacturer': '', 'deviceModel': '', 'androidVersion': '', 'registeredUser': {'userName': '', 'passwordHash': '', 'receivedHash': '', 'registeredTS': ''}, 'registeredDeviceID': '', 'lastAuthTS': ''}}
20220810_180147 digionline__read_stateData DEBUG: Exit function
20220810_180147 digionline__init_stateData DEBUG: __rsd__["exit_status"]: 0
20220810_180147 digionline__init_stateData DEBUG: Enter function
20220810_180147 digionline__read_stateData DEBUG: Enter function
20220810_180147 digionline__read_stateData DEBUG: Reading from 'C:\Users\admin\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.TVOnline.ro\digionline.ro_state.txt'
20220810_180147 digionline__read_stateData DEBUG: Return data: {'exit_status': 0, 'state_data': {'deviceID': '', 'deviceManufacturer': '', 'deviceModel': '', 'androidVersion': '', 'registeredUser': {'userName': '', 'passwordHash': '', 'receivedHash': '', 'registeredTS': ''}, 'registeredDeviceID': '', 'lastAuthTS': ''}}
20220810_180147 digionline__read_stateData DEBUG: Exit function
20220810_180147 digionline__check_DefaultUserSettings DEBUG: Enter function
20220810_180147 digionline__check_DefaultUserSettings DEBUG: 1. __ret__ = 0
20220810_180147 digionline__check_DefaultUserSettings DEBUG: 6. __ret__ = 1
20220810_180147 digionline__check_DefaultUserSettings DEBUG: 8. __ret__ = 1
20220810_180147 digionline__check_DefaultUserSettings DEBUG:  __ret__ = 1
20220810_180147 digionline__check_DefaultUserSettings DEBUG: Exit function
20220810_180147 digionline__init DEBUG: [digionline.ro] => Incomplete configuration => Please configure all fields for digionline.ro account.

**Comment by dilighiani** [comment]
Rezolvat. Poate fi sters acest issues.
Am gasit rezolvarea intr-un alt Issue inchis.

La campurile "Device Manufacturer", "Model", "Android version" trebuia pus:
Huawei
VOG_L29
10

Multumesc!

**Comment by cralin** [comment]
Probabil ca ai sarit cam prea repede peste [asta](https://github.com/cralin/plugin.video.TVOnline.ro/wiki#first-time-configuration):

"
    In the "Accounts" section, enable and fill-in all configuration fields shown for the platforms you want to access content from and then press the "OK" button.

NOTE: Details to be filled-in can be found at Settings -> About device section of your Android device. 
"
