### ISSUE TITLE
ProTV not working

### ISSUE THREAD

**Issue by Pappbox** [cralin/plugin.video.TVOnline.ro#15]
Salut, din cause scimbari la cont DIGI, am reinstalat plugin-ul si nu imi mai merge ProTVPlus

L-am mai instalat odata din nou, si acuma da eroare ca nu se poate incarca nici DIGI

**Comment by Pappbox** [comment]
[plugin.video.TVOnline.ro.log](https://github.com/cralin/plugin.video.TVOnline.ro/files/9483266/plugin.video.TVOnline.ro.log)

**Comment by cralin** [comment]
In log-ul atasat nu vad inca nimic "suspect"
Te rog sa adaugi si kodi.log de pe acelasi sistem si cu aceleasi timestamp-uri ca si cele din log-ul addon-ului

**Comment by Pappbox** [comment]
Ok, o sa fac. Culmea e, ca am reinstalat Totul, și Kodi, și acuma îmi spune ca dispozitivul a fost șters si trb reautorizat. Am redeschis Kodi de mii de ori, am schimbat parola, device name totul, și inca tot scrie ca trebuie reautorizat la DIgI.

proTv încarcă, si după ce apare ca a încărcat, sa se Închide

**Comment by cralin** [comment]
> Ok, o sa fac. Culmea e, ca am reinstalat Totul, și Kodi, și acuma îmi spune ca dispozitivul a fost șters si trb reautorizat. Am redeschis Kodi de mii de ori, am schimbat parola, device name totul, și inca tot scrie ca trebuie reautorizat la DIgI.

Sterge "digionline.ro_state.txt" si reporneste Kodi.

**Comment by Pappbox** [comment]
Am incercat, acuma imi merge DIGI24 dar la toate alte canale imi da eroare la pornire, ProTV nu merge nici cum

Cum gasesc kodi.log am un Mi TV BOX 4S

**Comment by cralin** [comment]
Nu esti in Romania sau nu ai adresa IP care este geolocata in Romania.

`2022-09-05 10:00:58.802 T:8193    ERROR <general>: AddOnLog: inputstream.adaptive: Could not open / parse manifest (https://edge213.rcs-rds.ro/V5-8561602-fe65171fc9b8c63b37dd79946c944656-3118590742-0-1662364858-25-musicchannel-02c001c4c08a9e4e/digionline/musicchannel-abr.m3u8?is=25&ns=musicchannel&p=Android&s=app&sn=ro.rcsrds.digionline&t=00000000000000000000000000000000&t4=V4-7364703-0ecbff514f271769e037157e55ee4ed1-3118590742-0-1662364858-25-musicchannel&t5=V5-8561602-fe65171fc9b8c63b37dd79946c944656-3118590742-0-1662364858-25-musicchannel-02c001c4c08a9e4e)`

**Comment by Pappbox** [comment]
Salut, dar culmea, pe calculator imi merge fara probleme cu acceasi VPN, si pana acuma tot asa o mers

**Comment by cralin** [comment]
al doilea kodi.log atasat de tine are 0 byes. e gol.

**Comment by Pappbox** [comment]
[kodi.log](https://github.com/cralin/plugin.video.TVOnline.ro/files/9489741/kodi.log)

**Comment by cralin** [comment]
Compara ce ai in calculator cu ce ai in Mi box din punct de vedere al VPN-ului

**Comment by Pappbox** [comment]
In calculator si pe iPhone am acceasi VPN -> NordVPN

**Comment by Pappbox** [comment]
Dar culmea inainte de reinstall a mers totul cum trb, acceasi vpn etc

**Comment by cralin** [comment]
Din moment ce problema care o ai nu este legata de addon in sine sau de functionalitatea acestuia am sa inchid acest issue.

**Comment by Pappbox** [comment]
Salut, cred ca este de la addon, poate nu de la al tau, dar poate de la altceva.

Am instalat KODI pe Windows, in browser digionline.ro imi merge, in Kodi doar DIGI24

Am facut poate ceva gresit la instalatie`?

**Comment by Pappbox** [comment]
`2022-09-05 22:33:14.093 T:17804    INFO <general>: Python interpreter stopped
2022-09-05 22:33:14.233 T:21456   ERROR <general>: CCurlFile::FillBuffer - Failed: HTTP returned error 401
2022-09-05 22:33:14.233 T:21456   ERROR <general>: CCurlFile::Open failed with code 401 for https://edge213.rcs-rds.ro/V5-6887564-4f33ed5da8c63fcd00e0e6a872e7c859-3118590870-0-1662409994-118-etnotv-210a25edf405573f/digionline/etnotv-abr.m3u8?is=118&ns=etnotv&p=Android&s=app&sn=ro.rcsrds.digionline&t=00000000000000000000000000000000&t4=V4-3024990-c77ce2ab9ff8ef3d224163cd4e49dddd-3118590870-0-1662409994-118-etnotv&t5=V5-6887564-4f33ed5da8c63fcd00e0e6a872e7c859-3118590870-0-1662409994-118-etnotv-210a25edf405573f:
                                                   
2022-09-05 22:33:14.233 T:21456   ERROR <general>: AddOnLog: inputstream.adaptive: Download failed: https://edge213.rcs-rds.ro/V5-6887564-4f33ed5da8c63fcd00e0e6a872e7c859-3118590870-0-1662409994-118-etnotv-210a25edf405573f/digionline/etnotv-abr.m3u8?is=118&ns=etnotv&p=Android&s=app&sn=ro.rcsrds.digionline&t=00000000000000000000000000000000&t4=V4-3024990-c77ce2ab9ff8ef3d224163cd4e49dddd-3118590870-0-1662409994-118-etnotv&t5=V5-6887564-4f33ed5da8c63fcd00e0e6a872e7c859-3118590870-0-1662409994-118-etnotv-210a25edf405573f
2022-09-05 22:33:14.233 T:21456   ERROR <general>: AddOnLog: inputstream.adaptive: Could not open / parse manifest (https://edge213.rcs-rds.ro/V5-6887564-4f33ed5da8c63fcd00e0e6a872e7c859-3118590870-0-1662409994-118-etnotv-210a25edf405573f/digionline/etnotv-abr.m3u8?is=118&ns=etnotv&p=Android&s=app&sn=ro.rcsrds.digionline&t=00000000000000000000000000000000&t4=V4-3024990-c77ce2ab9ff8ef3d224163cd4e49dddd-3118590870-0-1662409994-118-etnotv&t5=V5-6887564-4f33ed5da8c63fcd00e0e6a872e7c859-3118590870-0-1662409994-118-etnotv-210a25edf405573f)
2022-09-05 22:33:14.233 T:21456   ERROR <general>: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.TVOnline.ro/?action=play&account=digionline.ro&channel_id=118]`

**Comment by Pappbox** [comment]
Mi se pare ca vine de la inputstream.adaptive

**Comment by cralin** [comment]
Este din cauza ca adresa ta IP cu care ajungi la serverele digi ca sa faci play la continut nu este o adresa IP geolocata in Romania sau este filtrata de Digi.

De la mine este accesibil [acest URL](https://edge213.rcs-rds.ro/V5-6887564-4f33ed5da8c63fcd00e0e6a872e7c859-3118590870-0-1662409994-118-etnotv-210a25edf405573f/digionline/etnotv-abr.m3u8?is=118&ns=etnotv&p=Android&s=app&sn=ro.rcsrds.digionline&t=00000000000000000000000000000000&t4=V4-3024990-c77ce2ab9ff8ef3d224163cd4e49dddd-3118590870-0-1662409994-118-etnotv&t5=V5-6887564-4f33ed5da8c63fcd00e0e6a872e7c859-3118590870-0-1662409994-118-etnotv-210a25edf405573f) si vad continutul livrat de acel URL.

Nu imi raspunde cu 401 cind incerc sa-l accesez

**Comment by cralin** [comment]
Aici este un thread unde s-a mai discutat despre probleme similare legate de accesatul serviciilor prin VPN:

https://forum.softpedia.com/topic/1031230-kodi-xbmc/page__st__1620

Nu esti primul care are astfel de probleme.  ;)

**Comment by Pappbox** [comment]
deci sa înțeleg, sa schimb operatorul de VPN, chiar dacă îmi merge cu el pe alte dispozitive?

Von meinem iPhone gesendet

Am 05.09.2022 um 23:14 schrieb cralin ***@***.***>:

﻿

Aici este un thread unde s-a mai discutat despre probleme similare legate de accesatul serviciilor prin VPN:

https://forum.softpedia.com/topic/1031230-kodi-xbmc/page__st__1620

Nu esti primul care are astfel de probleme. ;)

**Comment by cralin** [comment]
Verifica setarile de pe dispozitivul de pe care nu iti merge acum.
Tot traficul de pe respectivul device ar trebui sa iasa prin VPN.

**Comment by Pappbox** [comment]
Salut, amn incercat pe acceasi VPN cu Kodi pe Windows si acum merge pe Windows

Doar pe Android TV adica MI BOX nu merge

**Comment by Pappbox** [comment]
Am facut downgrade la 19.2.6 si acum imi merge DIGI si pe MI BOX :)

Dar la ProTV inca da crash, si vreau sa raman pe 19.2.6 ca n.am voyo

**Comment by cralin** [comment]
diferenta dintre 19.2.6 si 19.2.9 este ca protvplus.ro a fost inlocuit cu voyo.ro in rest este la fel (partea de digi este acelasi cod in ambele versiuni.
