### ISSUE TITLE
Voyo.ro au abonament valabil imi da erroare ca nu am abonament.

### ISSUE THREAD

**Issue by Xdrqgol** [cralin/plugin.video.TVOnline.ro#16]
Sunt pe ultimul update lansat 19.2.8 , Digionline merge fara probleme dar voyo.ro nu merge deloc. 
Mentionez ca am incercat cu abonament valabil . Am reinstalat TVOnline.ro , refacut toate setarile - degeaba.

**Comment by cralin** [comment]
Rezolvat cu versiunea 19.2.9
