### ISSUE TITLE
500

### ISSUE THREAD

**Issue by victorMaf** [cralin/plugin.video.TVOnline.ro#17]
Dispozitiv șters eroare 500
Cum rezolv ?
Linux, Kodi 19

**Comment by cralin** [comment]
Salut,

Avind in vedere informatiile furnizate nu pot sa-ti zic nimic altceva decit "Works on my device" si sa inchid issue-ul acesta.

Vrei sa dai mai multe detalii despre ce eroare raportezi aici ?
