### ISSUE TITLE
Kodi se reseteaza la pornirea unui canal TV

### ISSUE THREAD

**Issue by sebastiancretu** [cralin/plugin.video.TVOnline.ro#19]
Salut!

De cateva saptamani addonul a inceput sa se reseteze (pe osmc) in momentul in care incerc sa pornesc un canal. Nu am reusit sa gasesc nimic in loguri, dar ce am observat este ca, acum mi se cere sa instalez widewine, iar dupa ce il instalez si incerc sa pornesc un canal, crapa. Inainte daca imi aduc bine aminte, nu se cerea instalarea widewine. S-a schimbat ceva in ultima versiune pe partea asta ?

Logurile se pot gasi aici: https://paste.osmc.tv/cidaneruze

**Comment by cralin** [comment]
Salut,
Nu am incercat deloc cu OSMC (eu folosesc addon-ul instalat intr-un LibreELEC 19 pe un RPI4 si merge fara probleme) insa este posibil sa fie ceva bug prin OSMC.

Iti zice sa instalezi Widewine fiindca vrei sa faci play la un stream DASH care este play-abil cu widewine.

**Comment by cralin** [comment]
Te rog sa activezi "Debug logging" in setarile addon-ului si dupa ce replici problema te rog sa-mi trimiti toate fisierele log generate de addon

Multumesc.

**Comment by sebastiancretu** [comment]
Salut.

Mersi pentru raspuns! Logul de sus e deja cu debugging activat la plugin. Totusi, pare ca problema vine de la ultimul widewine. Am facut un rollback la o versiune ce o avusesem la inceputul lunii, iar acum fuctioneaza.

Multumesc mult! Voi inchide tichetul.
