### ISSUE TITLE
Error kodi 19.0

### ISSUE THREAD

**Issue by woe66** [cralin/plugin.video.TVOnline.ro#2]
Installed In Xiaomi mi box 3s but error in kodi 19.0

![IMG_20210325_131151](https://user-images.githubusercontent.com/66027022/112469580-4fd3c980-8d72-11eb-9987-7d5c140c3d83.jpg)

**Comment by cralin** [comment]
Hi,
Nice picture but unfortunately does not really help in understanding where the problem might be.

Please enable debug logging in the addon, restart the kodi, replicate the issue and attach here all the *.log files from  [the location of add-on data files](https://github.com/cralin/plugin.video.TVOnline.ro/wiki#location-of-add-on-data-filesl)

Thank you.

**Comment by cralin** [comment]
Please also attach the **kodi.log** file present on the system after you\ve replicated the problem.

Thank you.

**Comment by woe66** [comment]
> Please also attach the **kodi.log** file present on the system after you\ve replicated the problem.
> 
> Thank you.

http://paste.ubuntu.com/p/prkngt6jWs/

**Comment by woe66** [comment]
Era de la idioțenia astora de la RDS care nu permit acces pentru mai mult de 5 dispozitive, mi am adus aminte după ce am transpirat o oră și jumătate încercând să copiez uploadez logurile din addon din tvbox mi 3s. Trebuiesc șterse dispozitivele din contul Digi, după aceea le înregistrează în ordinea conectării. Succes, se poate șterge/închide.
