### ISSUE TITLE
Folder custom pt fisierele PVR Simple IPTV pe AndroidTV 

### ISSUE THREAD

**Issue by clau-bucur** [cralin/plugin.video.TVOnline.ro#21]
E posibil sa adaugi o optiune pentru a salva fisierele necesare pt addonul `PVR Simple IPTV` intr-un alt folder ?

Rulez Kodi pe un Android TV Philips care nu-mi permite accesul la folderul `Android/data` unde-si stocheaza Kodi datele.
Am tot incercat diverse metode dar din pacare nu functioneaza niciuna.

Daca de ex. as putea configura addonul tau pt a salva fisierele in `/storage/emulated/0/Kodi/PVRSimple` problema ar fi rezolvata pt ca acea cale va fi accesibila din `PVR Simple IPTV`.

Multumesc frumos.

**Comment by clau-bucur** [comment]
Am reusit intre timp schimband locatia in care Kodi salveaza datele (https://kodi.wiki/view/HOW-TO:Change_data_location_for_Android) folosind ADB.

Oricum imi imaginez ca optiunea de care ziceam mai sus ar fi utila. E mult mai simplu de facut asta, decat sa mutam doate datele Kodi.

**Comment by johnnyslt** [comment]
Salut.

Si eu sunt interesat de posibilatatea salvarii fisierelor pt Simple IPTV in alt folder fara a muta DATA location pe  /storage/emulated. Deoarece asta impiedica addon-ul Elementum sa mai functioneza

Pe Chromecast Google TV Chromecast, android 12, Simple IPTV, nu poate accesa fisierele din plugin.video.TVOnline.ro

Merci !

**Comment by cralin** [comment]
Problema de care te lovesti este specifica pentru jucarele care ruleaza Android 11+ si nu prea are treaba cu addon-ul.
Parerea mea este ca, deocamdata, Kodi 19 este victima colaterala si cel mai probabil ca situatie va fi rezolvata cumva in Kodi 20

Daca vrei sa intelegi de ce in Android 11+ nu mai poti sa accesezi directorul "Android/data", ar trebui sa citesti despre [Scoped Storage](https://developer.android.com/about/versions/11/privacy/storage)

Daca vrei sa intelegi de ce addonul TVOnline.ro tine fisielele alea acolo unde le tine (si nu in alta parte), ar trebui sa citesti ce scrie prin documentatia Kodi despre:

    [Kodi data folder](http://kodi.wiki/view/Kodi_data_folder)
    [Userdata](http://kodi.wiki/view/Userdata)
    [addon_data](http://kodi.wiki/view/Userdata#addon_data)

In cazul in care vrei sa incerci sa ocolesti cumva problema care o ai, poate te ajuta sa citesti/faci ce scrie [aici](http://kodi.wiki/view/HOW-TO:Change_data_location_for_Android)

E posibil ca dupa ce ai facut tot ce scrie acolo sa trebuiasca sa iti reinstalezi toate addon-urile si sa-ti refaci toate setarile.
