### ISSUE TITLE
Posibilitate specificare ID digionline

### ISSUE THREAD

**Issue by clau-bucur** [cralin/plugin.video.TVOnline.ro#22]
Este posibila specificarea manuala a ID-ului dispozitivului conectat?
Astfel incat sa pot conecta mai multe deviceuri Kodi si numarul de dispozitive conectate sa nu fie afectat.
Se pare ca daca specific acelasi model si producator nu ajuta.

![image](https://user-images.githubusercontent.com/47672949/205100108-e2cdc7b5-8df1-4fbb-8c9f-561c081fcd24.png)

![image](https://user-images.githubusercontent.com/47672949/205101025-785007a7-9a2f-4ad8-a552-e94ff2ba5558.png)

**Comment by cralin** [comment]
Scuza-ma dar acesta ar insemna sa nu respecti in mod intentionat Termenii si Conditiile pentru serviciul Digionline.ro ceea ce, in acceptiunnea mea, inseamna pur si simplu abuz sau furt.

Deocamdata nu ma intereseaza sa sustin un astfel de comportament sau sa ajut la propagarea unui astfel de comportament.
