### ISSUE TITLE
playback failed in tvonline 

### ISSUE THREAD

**Issue by Catalinvl** [cralin/plugin.video.TVOnline.ro#24]
playback failed-one ore more items failed to play Kodi 20
[kodi.log](https://github.com/cralin/plugin.video.TVOnline.ro/files/10608683/kodi.log)
[plugin.video.TVOnline.ro.log](https://github.com/cralin/plugin.video.TVOnline.ro/files/10608691/plugin.video.TVOnline.ro.log)
Mulțumesc

**Comment by cralin** [comment]
In log-uri arata la fel cu ce s-a raportat [aici](https://github.com/xbmc/inputstream.adaptive/issues/715).
Din punctul meu de vedere problema nu este cu addon-ul ci mai degraba este cu tableta ta sau cu versiunea de Android care o rulezi pe respectiva tableta.

Am sa inchid acest issue fiindca nu are treaba cu addon-ul TVOnline.ro.
