### ISSUE TITLE
Kodi20.1

### ISSUE THREAD

**Issue by papichulo99** [cralin/plugin.video.TVOnline.ro#25]
Trebe să revert la 19 sa meargă iar? Ca îmi da eroare și nu îmi dau seama din log de ce. Mergea pe 19, dar a făcut auto update Kodi

Repository add-on repository.cralin.Kodi_19 does not have any directory and won't be able to update/serve addons! Please fix the addon.xml definition.

**Comment by cralin** [comment]
Salut,

repository.cralin.Kodi_19 nu are addon-ul pentru Kodi 20.

repository.cralin are addon-ul atit pentru Kodi 19 cit si pentru Kodi 20 si in functie de versiunea de Kodi care o folosesti iti instaleaza versiunea corecta de addon.

Dezinstaleaza addon-ul TVOnline.ro
Dezinstaleaza repository.cralin.Kodi_19
Install la repository.cralin asa cum scrie aici: https://github.com/cralin/repository.cralin
Din repository.cralin poti sa instalezi addon-ul TVOnline.ro (addons -> install from repository -> cralin's Repository -> Video add-ons)

Ultima versiune a addon-ului pentru Kodi 20 este 20.0.7.
