### ISSUE TITLE
Credentiale Gresite - Error 401

### ISSUE THREAD

**Issue by vladskz** [cralin/plugin.video.TVOnline.ro#27]
Salut, 
Intampin aceasta eroare de cand am facut update la kodi v19, dar si pe v20 intampin aceeasi problema. Am incercat si "pe curat" cu kodi reinstall si delete la folderul "Kodi".
Kodi 20.2 si 20.5 - pc si andoid - TV App sau Phone app => aceeasi eroare, 401, pentru digionline.

```
2024-03-31 22:14:27.416 T:25024   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: an integer is required (got type str)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\skizz\AppData\Roaming\Kodi\addons\plugin.video.TVOnline.ro\main.py", line 380, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "C:\Users\skizz\AppData\Roaming\Kodi\addons\plugin.video.TVOnline.ro\main.py", line 324, in router
                                                       digionline_functions.digionline__playVideo(params['behaveas'], params['channel_id'], common_vars.__AddonID__, common_vars.__digionline_Session__, MyAddon_DataDir)
                                                     File "C:\Users\skizz\AppData\Roaming\Kodi\addons\plugin.video.TVOnline.ro\resources\lib\digionline\functions.py", line 1280, in digionline__playVideo
                                                       digionline__phone_doAuth(NAME, SESSION, DATA_DIR)
                                                     File "C:\Users\skizz\AppData\Roaming\Kodi\addons\plugin.video.TVOnline.ro\resources\lib\digionline\functions.py", line 442, in digionline__phone_doAuth
                                                       common_vars.__logger__.debug('\'' + __rsd__['state_data']['registeredUser']['userName'] + '\' already registered at: ' + time.strftime("%Y%m%d_%H%M%S", time.gmtime(__rsd__['state_data']['registeredUser']['registeredTS'])))
                                                   TypeError: an integer is required (got type str)
                                                   -->End of Python script error report<--
                                                   
2024-03-31 22:14:27.503 T:17852   error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.TVOnline.ro/?account=digionline.ro&behaveas=Phone&action=play&channel_id=89]
2024-03-31 22:14:35.905 T:17852 warning <general>: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
```

Asta am extras din log in momentul erorii.

Multumesc.

**Comment by cralin** [comment]
Te rog sa-mi trimiti o copie a fisierelor log generae de add-on dupa ce ai activat in configuratia addon-ului optiunea "Enable debug logging"si i-ai dat un restart la kodi.

Fisierele log le gasesti in locatia descrisa aici:  https://github.com/cralin/plugin.video.TVOnline.ro/wiki#location-of-add-on-data-files

**Comment by vladskz** [comment]
Am adaugat 2 fisiere care au extensia log din folderul "Add-on Data"

[plugin.video.TVOnline.ro.log](https://github.com/cralin/plugin.video.TVOnline.ro/files/14892570/plugin.video.TVOnline.ro.log)
[service.plugin.video.TVOnline.ro.log](https://github.com/cralin/plugin.video.TVOnline.ro/files/14892571/service.plugin.video.TVOnline.ro.log)

**Comment by cralin** [comment]
Verifica in portatul digi.ro sa ai contul pentru digionline.ro activ si functional.
Daca nu ai aictivat, atunci activeaza-ti contul pentru digionline.ro si username-ul si parola pentru digionline.ro o configurezi in setarile addon-ului.

Daca nu iti merge login nici pe site-ul www.digionline.ro inseamna ca ai o problema cu respectivele credentiale. 
Poate ca un reset la parola pentru digionline.ro sa ajute.

**Comment by cralin** [comment]
Verifica sa introduci corect numerele de utilizator si parola.
in log-uri este raspunsul acesta:

"DEBUG: Received message: Numele de utilizator sau parola au fost introduse greșit"

**Comment by vladskz** [comment]
> Verifica in portalul digi.ro sa ai contul pentru digionline.ro activ si functional. Daca nu il ai aictivat, atunci activeaza-ti contul pentru digionline.ro iar username-ul si parola pentru digionline.ro le configurezi in setarile addon-ului.
> 
> Daca nu iti merge login nici pe site-ul [www.digionline.ro](http://www.digionline.ro) inseamna ca ai o problema cu respectivele credentiale. Poate ca un reset la parola pentru digionline.ro sa ajute.

Nu se pune problema, ziceam ca ma pot loga pe browser/aplicatia oficiala, dar prin varianta de login "Cu cont Digi(.)ro", sunt 2 variante de login pe digionline.
Am resetat parola, am facut pasii pe care i-ai dat, acum codul de eroare este 201009

Logul generat:
[plugin.video.TVOnline.ro.log](https://github.com/cralin/plugin.video.TVOnline.ro/files/14893757/plugin.video.TVOnline.ro.log)

**Comment by SileC** [comment]
Din log: "success":false,"errCode":"201009","message":"The username and\/or password that you have entered is incorrect.

**Comment by cralin** [comment]
@vladskz,

Verifica sa ai configurate corect username si paroa care le ai setate pentru contul digionline.ro (nu pentru digi.ro !)
In settings.xml din [[[ Kodi data directory ]](https://kodi.wiki/view/Kodi_data_folder#Location)/userdata/addon_data/plugin.video.TVOnline.ro][([[ Kodi data directory ]](https://kodi.wiki/view/Kodi_data_folder#Location)/userdata/addon_data/plugin.video.TVOnline.ro) poti sa-ti vezi username/parola in text clar.

Daca username/pass sint configurate corect in settings.xml, sterge fisierele digionline.ro_TVState.txt si digionline.ro_PhoneState.txt din [[[ Kodi data directory ]](https://kodi.wiki/view/Kodi_data_folder#Location)/userdata/addon_data/plugin.video.TVOnline.ro]([[ Kodi data directory ]](https://kodi.wiki/view/Kodi_data_folder#Location)/userdata/addon_data/plugin.video.TVOnline.ro) si da-i un restart la Kodi

Daca ai setat corect username/pass ar trebui sa-ti mearga dupa restart.

**Comment by vladskz** [comment]
Cred ca se poate inchide fiind caz izolat, nu?
Ce ati explicat am executat negresit, sunt in retea digi, am user si pass corect scrise in settings.xml. Verificat si reverificat. 
Pe browser si pe aplicatiile de mobil a digionline login-ul il fac prin "Cont digi(.)ro" din cele 2 variante(poza de mai sus). Cumva aceasta chestiune pare trecuta cu vederea, nestiind cum e configurat API-ul pe care il apeleaza scriptul.

Multumesc frumos de support si rabdare. :D

**Comment by cralin** [comment]
In addon-ul face login cu digionline (nu cu digi.ro) deci trebuie sa configurezi in addon username/pass pentru digionline.

Respectivul user/pass il creezi/generezi/administrezi din portatul digi.ro.

**Comment by cralin** [comment]
@vladskz 
Iti merge dupa ce ai configurat in addon credentialele pentru digionline.ro ?

**Comment by vladskz** [comment]
Salut,
M-am documentat iar modalitatea de a crea un user si pass specific pentru "digionline" nu mai e de actualitate
```
Cei ce au deja un cont Digi.ro (se poate configura în secțiunea Contul Meu), trebuie doar să instaleze aplicația Digi Online sau să acceseze în web digionline.ro. Logarea se poate face folosind datele de [conectare Digi](https://laptopnews.ro/instalarea-si-configurarea-router-ului-tplink-ax10-wifi6-digi/).ro, fără a mai fi nevoie de activarea serviciului Digi Online.

Altădată, pentru a utiliza serviciul Digi Online era necesară activarea acestui serviciu prin logarea  în contul Digi.ro, accesând Serviciile Mele, Digi Online, iar apoi activarea contului. Ulterior, pentru logarea în Digi Online, se folosea  adresa e-mail configurată pe contul Digi și parola aleasă. Conform reprezentanţilor Digi, acest lucru nu mai este necesar acum.
```
sursa: https://laptopnews.ro/logare-digi-online-cu-cont-digi-ro/

Pe site-ul digionline apare ca pot face asta, dar acel link ma trimite catre contul meu principal digi.ro (e inutil)
poza: 
![Screenshot 2024-04-12 084431](https://github.com/cralin/plugin.video.TVOnline.ro/assets/97524058/c781b9cf-0587-42be-97f6-7ad4049a872b)

o poza din contul meu digi la sectiune digionline: (unde am tras linia albastra este e-mail-ul contului general)

![435550233_787737879931552_576994328641908878_n](https://github.com/cralin/plugin.video.TVOnline.ro/assets/97524058/80baaca2-d030-4ff1-8b10-b2d8c8f7e994)

Multumesc.

**Comment by cralin** [comment]
Ce scrie la https://laptopnews.ro/logare-digi-online-cu-cont-digi-ro/ nu are nici o relevanta pentru acest thread.

Username-ul si parola care le-ai setat tu pentru serviciul digionline trebuie sa le configurezi in addon.
Aceleasi credentiale trebuie sa-ti functioneze daca le folosesti ca sa te logezi pe www.digionline.ro dupa ce ai ales "Login cu cont Digionline"

![image](https://github.com/cralin/plugin.video.TVOnline.ro/assets/47091655/29ba8cba-d153-43b4-9af7-0f7e15e7cb26)


Daca nu reusesti sa te contectizi pe www.digionline.ro cu credentialele (username/parola) pentru contul digionline atunci cel mai probabil ca folosesti parola gresita (sau ai uitat-o) pentru contul digionline si poti sa o resetezi din portalul digi.ro exact din sectiunea care se vede in screenshotul tau.

Ai acolo butonul "Schimba parola" sub "Dispozitive conectate".
Daca apesi pe el ai sa poti sa-ti schimbi parola pentru contul digionline.

**Comment by vladskz** [comment]
Am pus aici un filmulet cu behaviour-ul:
https://rumble.com/v4p12jx-digi.html
parola o completeaza browser-ul bine, reverificat.

**Comment by cralin** [comment]
Din film se vede ca iti da erorare cind faci login cu cont digionline.ro ceea ce (cel mai probabil) inseamna ca nu ai combinatia corecta de user/pass.
Acelasi lucru se vede si in log-urile addon-ului.

Schimba parola pentru contul digionline.ro si dupa ce ai schimbat verifica ca poti sa faci login pe digionline.ro cu username/parola pentru contul diginline.ro.

Daca poti sa faci login, acelasi username/pass  atunci configurezi si in addon exact acelasi userame/pass si ar trebui sa-ti meagra.
Daca merge login cu contul digionline.ro si nu merge addon-ul configurat cu aceleasi credentiale, te rog sa-mi trmiti o copie a log-urilor generate de addon.

**Comment by cralin** [comment]
Nu stiu ce parola iti completeaza automat browser-ul dar cu siguranta trebuie sa folosesti combinatia de username/parola care o ai configurata pentru contul digionline.ro. 
In nici un caz nu username/parola care le folosesti pentru accesarea portalului digi.ro

**Comment by cralin** [comment]
@vladskz
Iti merge dupa ce ai configurat in addon credentialele corecte pentru digionline.ro ?

**Comment by vladskz** [comment]
-am lipsit un pic de acasa-

Update:
Am luat incercat din nou cu parola noua si a functionat, totul este in regula. pe kodi v19 mergea ca in discutiile de mai sus, de la kodi v20 doar pana la 20.5, dupa kodi 20.5 a incetat sa ma functioneze cu cont "digi ro".

Multumesc mult.
