### ISSUE TITLE
login voyo cu orange (tv go)

### ISSUE THREAD

**Issue by maurerr** [cralin/plugin.video.TVOnline.ro#29]
salut,

in primul rand multumesc mult pentru tot efortul pe care il faci pentru acest addon !
Vreo sansa sa implementezi login cu orange (tv go) asa cum este in aplicatia de android?

Multumesc inca o data!

**Comment by cralin** [comment]
Salut,
Din pacate Orange TV (go sau no go :)  ) inca nu am reusit sa-l fac sa mearga. Dar nici nu am investit pre mult efort si timp sa-l fac sa mearga pentru.

Pntru autentificare in Voyo, merg credentialele care le ai pe platforma voyo.ro.

**Comment by maurerr** [comment]
merci pt raspuns

eu am voyo prin orange tv go - ma loghez cu acelasi cont (https://voyo.protv.ro/login?back_url=https%3A%2F%2Fvoyo.protv.ro%2F "Orange Romania SA"
