### ISSUE TITLE
IndexError: list index out of range in get_channels (functions.py)

### ISSUE THREAD

**Issue by mgrunca** [cralin/plugin.video.TVOnline.ro#3]
Menționez ca add-on-ul nu mai pare să îmi meargă nici pe Chromecast și nici pe Fire TV Stick, ambele cu Kodi Matrix și ultima versiune de add-on.

De asemenea menționez că pe contul de digionline am șters toate sesiunile, ca nu cumva problema să fie ca depășesc 5 sesiuni.

Logurile sunt aici:
https://we.tl/t-6VGb9hy7dD

Mulțumesc pentru muncă și ajutor!

**Comment by cralin** [comment]
Da, este din cauza ca s-au facut modificari pe site-ul digionline.ro

Inca nu am o solutie pentru problema.

**Comment by dumol** [comment]
Logurile nu mai îs online, dar bănuiesc că asta e eroarea:

```
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                Error Type: <class 'IndexError'>   
                Error Contents: list index out of range
                Traceback (most recent call last): 
                  File "/home/dumol/.kodi/addons/plugin.video.TVOnline.ro/service.py", line 335, in <module>
                    schedule.run_pending()             
                  File "/home/dumol/.kodi/addons/plugin.video.TVOnline.ro/resources/lib/schedule/__init__.py", line 601, in run_pending
                    default_scheduler.run_pending()    
                  File "/home/dumol/.kodi/addons/plugin.video.TVOnline.ro/resources/lib/schedule/__init__.py", line 97, in run_pending
                    self._run_job(job)                 
                  File "/home/dumol/.kodi/addons/plugin.video.TVOnline.ro/resources/lib/schedule/__init__.py", line 150, in _run_job
                    ret = job.run()                    
                  File "/home/dumol/.kodi/addons/plugin.video.TVOnline.ro/resources/lib/schedule/__init__.py", line 500, in run
                    ret = self.job_func()              
                  File "/home/dumol/.kodi/addons/plugin.video.TVOnline.ro/service.py", line 242, in PVRIPTVSimpleClientIntegration_init_m3u_file
                    PVRIPTVSimpleClientIntegration_update_m3u_file()
                  File "/home/dumol/.kodi/addons/plugin.video.TVOnline.ro/service.py", line 157, in PVRIPTVSimpleClientIntegration_update_m3u_file
                    _current_channel_number_ = digionline_functions.PVRIPTVSimpleClientIntegration_update_m3u_file(_tmp_m3u_file_, _current_channel_number_, common_vars.__ServiceID__, common_vars.__digionline_CookieJar__, common_vars.__digionline_ServiceSession__)
                  File "/home/dumol/.kodi/addons/plugin.video.TVOnline.ro/resources/lib/digionline/functions.py", line 1230, in PVRIPTVSimpleClientIntegration_update_m3u_file
                    channels = digionline_functions.get_channels(category['name'], NAME, COOKIEJAR, SESSION)
                  File "/home/dumol/.kodi/addons/plugin.video.TVOnline.ro/resources/lib/digionline/functions.py", line 757, in get_channels
                    _channel_metadata_ = _channel_metadata_[0].strip()
                IndexError: list index out of range
                -->End of Python script error report<--
                
INFO <general>: Python interpreter stopped
```

**Comment by cralin** [comment]
Fixed cu versiunea 19.2.0

**Comment by dumol** [comment]
Mulțam, am încercat să verific, dar se cer completate acele 3 noi variabile din configurare. Ghidul din wiki am văzut că nu e actualizat pentru noile variabile.

Cam care ar niște opțiuni valide? Și de ce îs lăsate oare la latitudinea utilizatorului precum contul și parola?

**Comment by rapi3** [comment]
Poti sa scrii aproape ce vrei tu acolo ca nu tuseste, putin mai greu e sa stergi default-ul din telecomanda.

DeviceManufacturer: Samung / Lenovo / Huawei...
DeviceModel: Galaxy / Tab / MatePad...
AndroidVersion: 5.0 /6.0 /7.0...

Pentru ca daca nu il folosesti pe android sa-l iei automat din dispozitiv e mai bine sa introduca userul ce vrea el decit sa ai niste presetari care sa le foloseasca toata lumea.

**Comment by cralin** [comment]
Pune acolo valori reale din Android-ul tau ca sa nu bata la ochi in log-urile de pe server cind se trimite request-ul.
Daca ai valori reale ar trebui sa iasa mai putin in evidenta ca este alt device decit unul real.

Informatiile le gasesti in Androidul tau in Settings -> About Device.

**Comment by cralin** [comment]
>  Și de ce îs lăsate oare la latitudinea utilizatorului precum contul și parola?

Pentru ca nu este normal sa fie optiunile alea hadcoded si nu am cum sa stiu ce fel de device foloseste fiecare.
;)

**Comment by dumol** [comment]
Mulțam, confirm că merge.

Instalările mele Kodi nu îs pe Android, personal aș prefera să fie trecut acolo ceva la la nimereală. Dacă fiecare variabilă ar fi randomizată dintr-o listă de 10 opțiuni, ar rezulta 1.000 de combinații posibile.

**Comment by cralin** [comment]
Nu trebuie sa ai instalarile numai pe Android, poti foarte bine sa le ai pe orcie hardware pe care merge Kodi.
Trebuie sa bagi datele alea in fiecare instalare (indiferent daca instalarea merge sau nu pe Android) ca sa poata addon-ul de pe instalarea respectiva sa se autentifice.
