### ISSUE TITLE
Error 0

### ISSUE THREAD

**Issue by ovitemp** [cralin/plugin.video.TVOnline.ro#31]
Salut.
Mai intai am ocazia sa-mi exprim admiratia pentru acest add-on pentru care sunt convins a s-a depus un volum de munca substantial.
Am instalat add-on-ul de cateva zile si mergea totul aproape bine, imi ramasese nelamurita o singura chestiune nu prea importanta... dupa activarea butonului de pauza, emisiunea continua foarte bine, dar nu am gasit cum pot derula inainte pentru a reveni la transmisia live. 
Folosesc un RaspberryPi4 si aseara add-on-ul functiona foarte bine. Nu am oprit aparatul dar am oprit streaming-ul, iar asta seara nu incarca nici un canal, mesajul este [digionline.ro] => Error 0
Evident am incercat restartare dar fara un rezultat pozitiv. Am incercat aplicatia pe telefon utilizand aceeasi legatura wi-fi si e OK. Am verificat conectivitatea la internet a Kodi.
Am activat debugging si restartat libreelec, atasez logurile.
[plugin.video.TVOnline.ro.log](https://github.com/user-attachments/files/17806137/plugin.video.TVOnline.ro.log)
[service.plugin.video.TVOnline.ro.log](https://github.com/user-attachments/files/17806138/service.plugin.video.TVOnline.ro.log)

**Comment by bonesawTM79** [comment]
Salut!

Haha - incredibil! Intampin aceeasi problema! Bineinteles ca sunt extrem de recunoscator pentru acest plug-in :)! L-am descoperit intamplator acum ceva vreme (de pe un forum vechi de pe softpedia) si tot pe un Raspberry Pi l-am instalat. 

Raspberry Pi 3 
Libreelec 12.0.1
Kodi v 21.1.0
TVOnline.ro version 21.0.6

[plugin.video.TVOnline.ro.log](https://github.com/user-attachments/files/17806906/plugin.video.TVOnline.ro.log)

@ovitemp - am comparat log-ul tau cu ce am eu si afara de credentials + hash-uri diferite - acceeasi problema. 

Speculez acuma dar poate face DIGI schimbari ale interfetei de acces programatic la digionline. 

Ca fapt divers, am resetat si parola de la digionline la mine si la fel. Accesarea din browser functioneaza, bineinteles.

**Comment by ovitemp** [comment]
Si eu m-am gandit ca poate Digi a schimbat ceva, asa ca asta seara am facut un simplu restart la libreelec si acum nu-mi mai arata nici macar lista grupurilor de canale. Presupun ca nu s-a facut actualizarea EPG.
Pentru ca pe telefon aplicatia functioneaza in continuare, am schimbat in setarile add-on-ului Behave as Phone App, fara alte schimbari si ... functioneaza, insa EPG nu este actualizat si nu functioneaza, probabil nu a ajuns la ora la care face update. 
Ideal ar fi insa sa poate functiona iar in modul TV

**Comment by bonesawTM79** [comment]
Am reusit sa il repornesc. Am reinstalat plugin-ul, l-am trecut in mode "Phone App" si am [refacut configurarile la PVR IPTV Client](https://github.com/cralin/plugin.video.TVOnline.ro/wiki#pvr-iptv-simple-client-integration). 

Ce am observat e ca dintr-un motiv sau altul, mi s-au resetat campurile din configurare, cele care descriu de pe ce "telefon" accesezi digionline. Le-am actualizat si vad ca functioneaza!

In momentul de fata, imi functioneaza la fel. Singura particularitate e ca stream-urile afisate sunt 720p. "Inainte" prindeam stream-uri 1080p. Dar pierderea de calitate nu e asa mare, mai ales ca schimb rezolutia TV-ului la 720p si il las pe el sa faca upscaling-ul. Arata exceptional!

@cralin - inca odata mii de multumiri pentru plugin! Functioneaza fantastic!

**Comment by ovitemp** [comment]
Eu nu am reinstalat plug-in, n-am schimbat nimic, doar modul din TV in Phone, dar este nevoie de restart.
Exact rezolutia 1080 este motivul pentru care preferam modul TV.

Dar poate autorul plug-in-ului ne va face o surpriza placuta rezolvand problema. Pana atunci mergem Phone mode.

**Comment by cralin** [comment]
De vreo citeva zile am si eu la mine in log-uri aceeasi eroare cu mesajul "An error occurred! Please try again!".
Inca nu am apucat sa studiez problema dar cu siguranta sint afectat si eu de aceeasi problema

Deocamdata am doar suspiciunea ca s-au schmbat API-urile pentru digionline TV.

**Comment by cralin** [comment]
Da, s-au schimbat API-urile pentru aplicatia pentru AndroidTV.

**Comment by 98c71be8** [comment]
Salut,
OSMC running Kodi 20.5,
TVOnline.ro version 20.0.20 instalat acum cateva minute

In loguri apare mesajul mentionat mai sus:

digionline__tv_getCategoriesChannels DEBUG: Received data: {"meta":{"error":{"code":0,"message":"An error occurred! Please try again!"}}}

**Comment by cralin** [comment]
Da corect, doar la aplicatia de TV s-au schimbat (deocamdata ?) API-urile.
E in cuptor deja fix-ul.

**Comment by cralin** [comment]
Rezolvat in ultimele versiuni de addon (21.0.7 si 20.0.21)

Am testat cu Kodi 21 (LibreELEC 12.0.1) pe un RPI4

@98c71be8,
Nu am mai testat cu Kodi 20 fiindca deja toate RPI-urile mele sint cu Kodi 21 (LibreELEC 12.0.1)
Daca nu merge pe Kodi 20, te rog sa adaugi un comment in thread-ul acesta.

**Comment by bonesawTM79** [comment]
Merge si la mine 21.0.7

RP5
LibreElec 12.0.1

Acuma l-am pus. Mod TV se vede perfect!

@cralin Felicitari si multe multumiri!

**Comment by 98c71be8** [comment]
Salut,
Am lăsat Pi-ul pornit peste noapte și a trecut la versiunea Kodi 21.
Așa că pot confirma că add-on-ul a trecut la 21.0.7 și merge atât în Mod TV cât și în mod Phone App.

Mulțumesc !

On November 23, 2024 8:36:27 PM UTC, "cralin " <> wrote:
>
>--------------------------IronVest---------------------------
>Preview: Rezolvat in ultimele versiuni de addon (21.0.7 si 20.0.21) Am --> SPAM? CLICK to BLOCK: ***@***.***/toggle
>
>This email is Masked using Ironvest - it was sent from github.com to ***@***.*** (your reply stays Masked). To protect your privacy, do not forward this message, or add new recipients like CCs or BCCs.
>
>Thanks for being an IronVest customer!
>--------------------------IronVest---------------------------
>
>Rezolvat in ultimele versiuni de addon (21.0.7 si 20.0.21)
>
>Am testat cu Kodi 21 (LibreELEC 12.0.1) pe un RPI4
>
>@98c71be8,
>Nu am mai testat cu Kodi 20 fiindca deja toate RPI-urile mele sint cu Kodi 21 (LibreELEC 12.0.1)
>Daca nu merge pe Kodi 20, te rog sa adaugi un comment in thread-ul acesta.
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/cralin/plugin.video.TVOnline.ro/issues/31#issuecomment-2495647660
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
--
HRTS GOGU 

Please excuse my typos and brevity. Sent from a Smartphone.

**Comment by bonesawTM79** [comment]
@98c71be8 - joaca-te aici cu cache size-ul de la Kodi (stream-urile 1080p au bitrate mai mare decat 720p pe PhoneApp) - vezi aici https://kodi.wiki/view/Settings/Services/Caching

Eu am pus - Buffer all filesystems, including local files, 96 MB memory size, chunksize 256kb (restul default). Merge ata si pe RP5 si pe RP3.

**Comment by 98c71be8** [comment]
Nu am gasit nimic specific asa ca am exportat logurl din 2024-11-25 cu incepere de la momentul cand apare in log plugin.video.TVOnline.ro v21.0.7 installed pana la sfarsitul zilei de 2024-11-25 cand am dat shut down la OSMC

grep 'plugin.video.TVOnline.ro' ~/.kodi/temp/kodi.log
2024-11-25 22:16:16.084 T:359      info <general>: CAddonMgr::FindAddons: plugin.video.TVOnline.ro v21.0.7 installed
2024-11-26 20:54:52.259 T:503      info <general>: CAddonMgr::FindAddon: plugin.video.TVOnline.ro v21.0.8 installed

Dupa cum se vade mai sus astazi s-a instalat v21.0.8
[kodi_2024-11-25.log](https://github.com/user-attachments/files/17924724/kodi_2024-11-25.log)

**Comment by ovitemp** [comment]
Am asteptat sa vad rezultatul celorlalti utilizatori. La mine nici versiunea 7 nici 8 nu functioneaza cand comut pe modul TV (apoi restart system).
Nu stiu daca este nevoie de log-uri sau poate doar sa mai astept o noua versiune. Stiu ca e greu de gasit solutii si este nevoie de timp.

**Comment by cralin** [comment]
TV merge doar daca esti in reteaua Digi (ai internet de la Digi).
La mine merge versiunea 21.0.8 pe RPi 4 cu LibreELEC.

Seteaza in configuratia addon-ului: 
"Behave As: TV APP"
"Enable debug logging"   <-optinunea trebuie sa fie activa

Restart la Kodi si apoi apoi mergi la Videos -> Addons -> TVOnline.ro -> digionline.ro -> HD  si incearca sa faci play la un stream din lista.

Daca nu iti merge, trimite-mi te rog fisierele complete:
~/.kodi/temp/kodi.log
~/.kodi/userdata/addon_data/plugin.video.TVOnline.ro/service.plugin.video.TVOnline.ro.log
~/.kodi/userdata/addon_data/plugin.video.TVOnline.ro/plugin.video.TVOnline.ro.log

**Comment by ovitemp** [comment]
Salut, multumesc pentru ajutor in rezolvarea problemei.
Evident ca sunt conectat la reteaua Digi, altfel nu ar merge addon-ul nici pe modul telefon.
Am acelasi RPi 4, LibreELEC si 21.08. (upgraded de la 21.07-21.08)
Acum am facut chiar de 2 ori restart, am intrat de pe telefon in aplicatia Digi si am sters vechiul ID ca sa fiu sigur ca am doar 4 dispozitive in lista (desi addonul a creat ID-ul din versiunea 21.0.6 si nu am schimbat nimic pana azi).
Fara sa schimb nimic altceva, daca schimb in modul telefon, addonul functioneaza excelent.
Tocmai ma voi apuca sa reinstalez de la zero pe RPi 3 cel vechi LibreELEC si addon-ul, voi reveni cu feed-back.
Atasez log-urile de pe RPi4 care nici macar nu intra in lista de canale, adica nu pot ajunge la selectarea stream-ului.
[plugin.video.TVOnline.ro.log](https://github.com/user-attachments/files/17968603/plugin.video.TVOnline.ro.log)
[service.plugin.video.TVOnline.ro.log](https://github.com/user-attachments/files/17968604/service.plugin.video.TVOnline.ro.log)

**Comment by cralin** [comment]
Serge fisierul .kodi/userdata/addon_data/plugin.video.TVOnline.ro/digionline.ro_TVState.txt si incearca din nou.

**Comment by ovitemp** [comment]
"Esti mare boss..." :-)
Functioneaza.
A aparut scurt timp un mesaj de eroare, motiv pentru care atasez noile log-uri daca ajuta cu ceva in dezvoltarea aplicatiei, insa problema este rezolvata.
Desi eram 99% convins ca daca as fi sters complet addon-ul, restart si reinstalare ar fi mers, nu m-am grabit sa o fac in speranta ca poti afla ce a produs problema si sa nu se repete in upgrade-urile viitoare.
Multumesc mult, inca odata felicitari pentru acest addon atat de folositor.
Iti doresc o zi excelenta. 
[plugin.video.TVOnline.ro.log](https://github.com/user-attachments/files/17968800/plugin.video.TVOnline.ro.log)
[service.plugin.video.TVOnline.ro.log](https://github.com/user-attachments/files/17968801/service.plugin.video.TVOnline.ro.log)

**Comment by cralin** [comment]
Versiunile 21.0.9 si 20.0.23 rezolva din cod treaba pentru situatia in care ai fost tu.

**Comment by ovitemp** [comment]
Am reusit sa instalez fara probleme majore si pe RPi3 LibreELEC 12.0.1 apoi cralin repository si addon-ul 21.0.9, functioneaza din prima fara probleme in modul TV si cu PVR IPTV Simple Client.

Singura piedica am avut-o din cauza compatibilitatii LibreELEC 12.0.1 cu monitorul folosit, pur si simplu monitorul nu avea imagine. Am descoperit ca versiunea 9 mergea si dupa upgrade la 12 problema reaparea. Secretul era rezolutia. Am folosit alt TV si am setat rezolutia la 1080p.
Salutari si multumiri, multa sanatate
