### ISSUE TITLE
Suport pentru voyo.ro

### ISSUE THREAD

**Issue by dumol** [cralin/plugin.video.TVOnline.ro#5]
Salut,

Doar o sugestie! Ar fi fain de ar merge și voyo.ro, acum că meciurile de la Euro 2020 se văd doar acolo.

Interfața e similară celei de la protvplus.ro, poate nu-i mult de lucru… Stream-urile live merg și cu un cont de încercare, costă 0,25 lei parcă.

**Comment by cralin** [comment]
Meciurile de la Euro 2020 se vad pe stream-ul PROTV care il vezi cu cont de protvplus.ro.

Iti arata mesajul cu abonament de Voyo pentru ca ajungi la serverele *.protvplus.ro cu adresa IP din afara Romaniei.

**Comment by dumol** [comment]
Mulțam pentru răspuns! Nu am adresă IP din afara României. Am problema asta în 2 locuri diferite cu abonamente diferite Digi.

Din ce văd, într-adevăr se pot vedea meciurile Euro 2020 cu acest plugin DACĂ e pornit dinainte să înceapă transmisiunea meciurilor. Însă de ies din Kodi și îl pornesc din nou, nu mai merge…

Nicio eroare nu apare prin loguri, maxim văd asta când schimb canalul:
```
20210621_190236 do_login INFO: Already authorized.
```

Celelalte canale, de exemplu Pro Cinema, merg fără probleme cât timp Pro TV sau Pro X au meciuri Euro 2020.

**Comment by dumol** [comment]
Pe de altă parte, am observat că stream-urile live Voyo nu îs protejate DRM. Poate ajută… :D

**Comment by cralin** [comment]
Imi trimiti te rog log-urile generate de addon dupa ce ai activat debug logging si ai replicat problema ?

Mai ales atunci cind pro-cinema iti merge si protv nu.

Te rog sa incluzi si "kodi.log"

**Comment by dumol** [comment]
Logul de debug al plugin-ului când încerc Pro TV și nu merge pentru că-i meci Euro 2020: https://gist.githubusercontent.com/dumol/e5857f0faa6413e733e3b03da0f9c32a/raw/e4cb38538fd55fa3c2991d945b92432ddee0f992/gistfile1.txt

Logul de debug Kodi corespunzător: https://gist.githubusercontent.com/dumol/f2868b9bb4898cd558c8e71f4fb74978/raw/9dc88b76cec62924ea15cd0779092b72a7d84672/gistfile1.txt

**Comment by cralin** [comment]
Cred ca mai degraba ai o problema legata de instalarea ta de Kodi decit de plugin.video.TVOnline.ro

In kodi.log ai asta: 
```

2021-06-21 19:23:57.669 T:22103   DEBUG <general>: AddOnLog: inputstream.adaptive: Download https://cmero-ott-vod-prep-prot.ssl.cdn.cra.cz/vod_cmero/_definst_/0123/4753/rum-sd0-sd1-sd2-sd3-sd4-hd1-hd2-axinom-DTTIx2Oc.smil/chunklist_b5251072.m3u8 finished
2021-06-21 19:23:57.669 T:22103   FATAL <general>: AddOnLog: inputstream.adaptive: Unsupported encryption method: SAMPLE-AES
2021-06-21 19:23:57.669 T:22103   DEBUG <general>: AddOnLog: inputstream.adaptive: GetStream(1001)
2021-06-21 19:23:57.669 T:22103 WARNING <general>: OpenStream - Unsupported stream 1001. Stream disabled.

```

Tot in Kodi .log se vede ca rulezi kodi pe "Platform: Linux x86 64-bit".

Vrei sa pornesti pe masina respectiva un LibreELEC de pe un stick USB si sa vezi daca iti arunca aceleasi erori ?

**Comment by cralin** [comment]
La mine merge stream-ul fara probleme pe un RPI4 cu [LibreELEC nightly-20210611-f547d15](http://test.libreelec.tv/LibreELEC-RPi4.arm-10.0-nightly-20210611-f547d15.tar)

Incearca prima data sa pornesti o masina viruala cu https://test.libreelec.tv/LibreELEC-Generic.x86_64-10.0-nightly-20210621-ef9b52d.ova

**Comment by dumol** [comment]
Deci îți merge chiar de repornești rPI-ul în timpul meciului?

Pentru că a doua instalare pe care am testat e chiar un rPI cu LibreELEC nightly și am exact aceeași problemă.

**Comment by cralin** [comment]
Dap, imi merge daca pornesc in timpul meciului

asta am mai facut in instalarea mea:
`echo "LD_PRELOAD=/usr/lib/libtcmalloc_minimal.so" > /storage/.config/kodi.conf
reboot`

Asa cum este descris aici:   https://libreelec.tv/2021/05/le-9-2-7-10b4-fix-widevine/

**Comment by cralin** [comment]
Incearca prima data sa faci asta:

`echo "LD_PRELOAD=/usr/lib/libtcmalloc_minimal.so" > /storage/.config/kodi.conf`
`reboot`

**Comment by dumol** [comment]
Nu e vorba de deschis canalul în timpul meciului. Pentru că dacă e pornit deja Kodi și plugin-ul tău, atunci vor merge și meciurile. Încearcă te rog să repornești RPI-ul cu totul.

Stream-urile live ale meciurilor Euro 20202 nu îs codate DRM nici pe Voyo. Dar, mă rog, oricum n-am probleme cu Widevine nici pe desktop, nici pe RPI. Am HBO Go și Netflix funcționale pe ambele.

În fine, acest issue era despre suport voyo.ro. Dacă se poate…

**Comment by cralin** [comment]
Am sa arnc o privire si la Voyo ca platforma de continut media (presupunind ca pot sa-mi fac un cont fara sa platesc degeaba bani pentru ceva ce voi folosi doar pentru testing) insa nu iti promit ca se va intimpla peste noapte si/sau va fi ceva functional pina se termina Europenele.

**Comment by dumol** [comment]
Nicio problemă! Contul de încercare 7 zile costă 0,25 lei parcă.

**Comment by dumol** [comment]
În ce privește funcționalitatea protvplus.ro, e fain că merg meciurile dacă plugin-ul e pornit din timp, asta-mi acoperă 80% din nevoi.

**Comment by cralin** [comment]
Pe al doilea RPI4 imi arunca si mie aceeasi eroare in kodi.log
O sa le compar sa vad ce este diferit intre ele

**Comment by cralin** [comment]
Cred ca am gasit ce cautam.
Va fi un update de addon zilele astea.

**Comment by dumol** [comment]
Excelent! Aștept cu interes… ;-]

**Comment by cralin** [comment]
ai cont pe voyo la care poti/vrei sa-mi dai acces sa vad ce e pe portalul voyo  ?

Mie nu vrea voyo sa-mi ia din cont 0.05 EUR

**Comment by dumol** [comment]
Da, dă-mi te rog o adresă de mail.

**Comment by cralin** [comment]
cralin la gmail punct com

**Comment by marmarse** [comment]
@cralin - este posibil ca programele ProTV sa fie incluse in aceeasi lista m3u ca cele Digi? 
a.i. sa fie o lista globala in PVR client?

**Comment by cralin** [comment]
Acest addon genereaza o sigura lista m3u in care sint incluse toate stream-urile accesibil de pe platformele pentru case este configurat addon-ul.
Daca ai activat si configurat detaliile de autentificare pentru digionline.ro si cele pentru protvplus.ro, atunci lista m3u gestionata de acest addon va contine canalele de la digi cit si cele de la protv

**Comment by marmarse** [comment]
Am setat conform tuturial, intai pentru Digi, am deschis PVR client si am toate canalele Digi.

Apoi am incercat sa configurez si pentru ProTV, din plugin TVOnline s-au deschis posturile, dar in PVRclient nu erau in lista.
(user/parola sunt ok din browser pe  https://protvplus.ro/ )

Dupa restart nu mai merge sa deschid ProTV nici din plugin, imi genereaza urmatoarea eroare:
(pe tv cu android)

`ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.TVOnline.ro/service.py", line 331, in <module>
                                                       schedule_jobs()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.TVOnline.ro/service.py", line 134, in schedule_jobs
                                                       PVRIPTVSimpleClientIntegration_init_m3u_file()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.TVOnline.ro/service.py", line 205, in PVRIPTVSimpleClientIntegration_init_m3u_file
                                                       PVRIPTVSimpleClientIntegration_update_m3u_file()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.TVOnline.ro/service.py", line 242, in PVRIPTVSimpleClientIntegration_update_m3u_file
                                                       _current_channel_number_ = protvplus_functions.PVRIPTVSimpleClientIntegration_update_m3u_file(_tmp_m3u_file_, _current_channel_number_, common_vars.__ServiceID__, common_vars.__protvplus_CookieJar__, common_vars.__protvplus_ServiceSession__)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.TVOnline.ro/resources/lib/protvplus/functions.py", line 551, in PVRIPTVSimpleClientIntegration_update_m3u_file
                                                       channels = protvplus_functions.get_channels(NAME, COOKIEJAR, SESSION)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.TVOnline.ro/resources/lib/protvplus/functions.py", line 495, in get_channels
                                                       _channel_id_ = re.findall(_channel_url_ + '" data-channel-id="(.+?)"', _request_.content.decode(), re.IGNORECASE|re.DOTALL)[0]
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--`

**Comment by cralin** [comment]
Problema respectiva este rezolvata in versiunea [19.2.5](https://github.com/cralin/plugin.video.TVOnline.ro/releases/tag/19.2.5).

**Comment by marmarse** [comment]
Multumesc pentru raspunsul rapid, confirm ca merge perfect acum cu versiunea 19.2.5 (inclusiv lista din PVRclient)

Foarte util proiectul, sa ai putere si chef de munca pentru a-l sustine in continuare !!

**Comment by cralin** [comment]
In versiunea 19.2.9 protvplus.ro a fost inlocuit cu Voyo.

**Comment by dumol** [comment]
Mișto, felicitări!

Ca să nu mă afurisească degeaba cei ce folosesc protvplus.ro, sugestia mea era să meargă și voyo.ro în paralel cu protvplus.ro.  Personal, am folosit voyo.ro doar în timpul campionatului european de fotbal, dar contul gratuit protvplus.ro îl folosesc mai des…

**Comment by cralin** [comment]
oricum nu mai mergea protvplus.ro
;)
