### ISSUE TITLE
Wiki: Please configure all fields for digionline.ro account.

### ISSUE THREAD

**Issue by 98c71be8** [cralin/plugin.video.TVOnline.ro#7]
Salut,
Wiki nu contine detalii despre toti parametrii necesari a fi configuratoi pt ca add-on sa mearga:
Ca sa mearga add-on este necesara si configurarea parametrilor 'deviceManufacturer': '', 'deviceModel': '', 'androidVersion': '', altfel add-on afiseaza 
DEBUG: [digionline.ro] => Incomplete configuration => Please configure all fields for digionline.ro account.

Am folosit:
<setting id="digionline_DeviceManufacturer">Huawei</setting>
    <setting id="digionline_DeviceModel">VOG_L29</setting>
    <setting id="digionline_AndroidVersion">10</setting>

Iata cum apare in DigiOnline acest dispozitiv

Id: xxxxxx-yyyyyy-zzzzzz
Producător: Huawei
Model: VOG_L29
Data inregistrarii:.....

PS: Kodi 19.1 versionea din August 2021

**Comment by cralin** [comment]
Salut, 

In mintea mea cumva se face conexiunea ca trebuia sa completez toate cimpurile daca primesc mesajul de la addon ca virgula configuratia nu e completa si imi spune sa configurez toate cimpurile pentru provider-ul respectiv (mentionat in mesajul de pe ecran).

In orice caz, acuma scrie si in wiki sa completezi toate cimpurile de configurare care iti sint prezentate.

;)
