### ISSUE TITLE
Liste m3u in Live Channels - Android TV

### ISSUE THREAD

**Issue by ihrapsa** [cralin/plugin.video.TVOnline.ro#8]
Salutare,

Apreciez foarte mult acest plugin în Kodi însă aș avea o întrebare legată de vizualizarea stream-urilor prin aplicația Live Channels pe Android TV folosind aplicatiile PVR Live sau TVirl. Acestea doua din urma preiau fișierele playlist m3u și le configurează ca și surse în Live Channels. 

Fisierul m3u generat de plugin în kodi are caile url începând cu `plugin://` și probabil de aceea eșuează în PVR Live sau TVirl. Exista vreo posibilitate de a genera URLs care merg direct la stream? 

Pentru PRO TV din protvplus.ro un exemplu ar fi:
`https://protvplus.ro/api/v1/user/live?v=*************&ch=1`
Însă acesta nu merge fără cookie sau ceva token cred. Nu-mi dau seama cum ar putea fi integrat în link și cookie-ul creat de plugin.

Mersi mult!!

**Comment by cralin** [comment]
Salut, 
Scopul fisierelor generate de acest addon este ca ele sa fie utilizate cu un Kodi in care ai instalat si configurat acest addon. 

Probabil se poate face ce sugerezi tu insa nu aceasta este intentia cu acest addon pentru Kodi si cel mai probabil va trebui implementat de altcineva.

**Comment by ihrapsa** [comment]
Da, fișierele funcționează perfect in PVR Simple IPTV. Probabil acesta folosește și cookie-ul generat de addon Și de accea streamurile sunt vizibile. In aplicația de android PVR Live/TVirl va trebui probabil să folosesc o abordare similara. Nu prea am experiență în asta dar voi incerca să găsesc o soluție la problema.  Merci oricum de răspuns!
