### ISSUE TITLE
Channels/EPG don't show the ProTV channels

### ISSUE THREAD

**Issue by dsbenghe** [cralin/plugin.video.TVOnline.ro#9]
Hi,

All the digionline channels are correctly showing and working in Channels/EPG/... via PVR Simple IPTV but not the ProTV channels. I can still watch the ProTV channels via AddOn entry-point.

Is that expected? Am I doing something wrong?

**Comment by cralin** [comment]
No reaction in the last 10 days thus I assume this issue is no longer relevant/needed.
